(define (square x)
  (* x x))

(define (sum-of-squares-larg a b c)
  (cond ((and (>= a b) (>= a c))
	 (if (> b c)
	     (+ (square a) (square b))
	     (+ (square a) (square c))))
	((and (>= b a) (>= b c))
	 (if (> a c)
	     (+ (square b) (square a))
	     (+ (square b) (square c))))
	(else (if (> a b)
		  (+ (square c) (square a))
		  (+ (square c) (square b))))))
